### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AShabana** [CyCoreSystems/netdiscover#4]

**Comment by Ulexus** [comment]
Are you kidding?  ifconfig.me does not even have an IPv6 endpoint.
Moreover, if is just a standard STUN-style discoverer (with a bunch of other scraped data, too, which is superfluous for this tool).  It also does not appear to be machine-readable.
This is why we use `jsonip.io` for this tool.  It handles both IPv4 and IPv6, and it outputs the data in JSON.

Beyond that, this is a tool for cloud-based resources, too, which is why we integrate with the cloud-suppliers' APIs.
